/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CakeryV5RouteImport } from './routes/cakery-v5'
import { Route as CakeryV4RouteImport } from './routes/cakery-v4'
import { Route as CakeryV3RouteImport } from './routes/cakery-v3'
import { Route as CakeryV2RouteImport } from './routes/cakery-v2'
import { Route as CakeryRouteImport } from './routes/cakery'
import { Route as CafeRouteImport } from './routes/cafe'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CakeryV5Route = CakeryV5RouteImport.update({
  id: '/cakery-v5',
  path: '/cakery-v5',
  getParentRoute: () => rootRouteImport,
} as any)
const CakeryV4Route = CakeryV4RouteImport.update({
  id: '/cakery-v4',
  path: '/cakery-v4',
  getParentRoute: () => rootRouteImport,
} as any)
const CakeryV3Route = CakeryV3RouteImport.update({
  id: '/cakery-v3',
  path: '/cakery-v3',
  getParentRoute: () => rootRouteImport,
} as any)
const CakeryV2Route = CakeryV2RouteImport.update({
  id: '/cakery-v2',
  path: '/cakery-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const CakeryRoute = CakeryRouteImport.update({
  id: '/cakery',
  path: '/cakery',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeRoute = CafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cafe': typeof CafeRoute
  '/cakery': typeof CakeryRoute
  '/cakery-v2': typeof CakeryV2Route
  '/cakery-v3': typeof CakeryV3Route
  '/cakery-v4': typeof CakeryV4Route
  '/cakery-v5': typeof CakeryV5Route
  '/contact': typeof ContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cafe': typeof CafeRoute
  '/cakery': typeof CakeryRoute
  '/cakery-v2': typeof CakeryV2Route
  '/cakery-v3': typeof CakeryV3Route
  '/cakery-v4': typeof CakeryV4Route
  '/cakery-v5': typeof CakeryV5Route
  '/contact': typeof ContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cafe': typeof CafeRoute
  '/cakery': typeof CakeryRoute
  '/cakery-v2': typeof CakeryV2Route
  '/cakery-v3': typeof CakeryV3Route
  '/cakery-v4': typeof CakeryV4Route
  '/cakery-v5': typeof CakeryV5Route
  '/contact': typeof ContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cafe'
    | '/cakery'
    | '/cakery-v2'
    | '/cakery-v3'
    | '/cakery-v4'
    | '/cakery-v5'
    | '/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cafe'
    | '/cakery'
    | '/cakery-v2'
    | '/cakery-v3'
    | '/cakery-v4'
    | '/cakery-v5'
    | '/contact'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cafe'
    | '/cakery'
    | '/cakery-v2'
    | '/cakery-v3'
    | '/cakery-v4'
    | '/cakery-v5'
    | '/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CafeRoute: typeof CafeRoute
  CakeryRoute: typeof CakeryRoute
  CakeryV2Route: typeof CakeryV2Route
  CakeryV3Route: typeof CakeryV3Route
  CakeryV4Route: typeof CakeryV4Route
  CakeryV5Route: typeof CakeryV5Route
  ContactRoute: typeof ContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cakery-v5': {
      id: '/cakery-v5'
      path: '/cakery-v5'
      fullPath: '/cakery-v5'
      preLoaderRoute: typeof CakeryV5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cakery-v4': {
      id: '/cakery-v4'
      path: '/cakery-v4'
      fullPath: '/cakery-v4'
      preLoaderRoute: typeof CakeryV4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cakery-v3': {
      id: '/cakery-v3'
      path: '/cakery-v3'
      fullPath: '/cakery-v3'
      preLoaderRoute: typeof CakeryV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cakery-v2': {
      id: '/cakery-v2'
      path: '/cakery-v2'
      fullPath: '/cakery-v2'
      preLoaderRoute: typeof CakeryV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cakery': {
      id: '/cakery'
      path: '/cakery'
      fullPath: '/cakery'
      preLoaderRoute: typeof CakeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe': {
      id: '/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof CafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CafeRoute: CafeRoute,
  CakeryRoute: CakeryRoute,
  CakeryV2Route: CakeryV2Route,
  CakeryV3Route: CakeryV3Route,
  CakeryV4Route: CakeryV4Route,
  CakeryV5Route: CakeryV5Route,
  ContactRoute: ContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
